name: mutable_copy_generator
description: Mutable copy generator.
version: 0.2.0
repository: https://github.com/AlexVegner/mutable_copy_generator
issue_tracker: https://github.com/AlexVegner/mutable_copy_generator/issues
homepage: https://github.com/AlexVegner/mutable_copy_generator

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  analyzer: ">=0.39.0 <1.0.0"
  build: ^1.2.2
  path: ^1.7.0
  mutable_copy: ^0.1.3
  source_gen: ^0.9.5

dev_dependencies: 
  build_config: ^0.4.2
  build_runner: ^1.9.0
  test: ^1.14.2
